ydlidar_node:
  ros__parameters:
    port: /dev/YDLIDAR
    frame_id: base_scan
    ignore_array: ""
    baudrate: 128000
    samp_rate: 5
    resolution_fixed: true
    singleChannel: true
    auto_reconnect: true
    reversion: true
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 12.0
    min_range: 0.1
    frequency: 10.0
